### ISSUE TITLE
TransactionTooLargeException

### ISSUE THREAD

**Issue by KYHSGeekCode** [KYHSGeekCode/Android-Disassembler#113]
Sometimes crashes the app

**Comment by KYHSGeekCode** [comment]
Maybe fixed by using viewpager2

**Comment by KYHSGeekCode** [comment]
2020-03-07 23:56:31.026 17474-18098/com.kyhsgeekcode.disassembler W/FA-Ads: Got on activity created
2020-03-07 23:56:31.569 17474-17544/com.kyhsgeekcode.disassembler D/EGL_emulation: eglMakeCurrent: 0xe6285d80: ver 3 1 (tinfo 0xe62834b0)
2020-03-07 23:56:31.788 17474-17544/com.kyhsgeekcode.disassembler D/EGL_emulation: eglMakeCurrent: 0xe6285d80: ver 3 1 (tinfo 0xe62834b0)
2020-03-07 23:56:31.854 17474-17544/com.kyhsgeekcode.disassembler D/EGL_emulation: eglMakeCurrent: 0xe6285d80: ver 3 1 (tinfo 0xe62834b0)
2020-03-07 23:56:32.419 17474-17474/com.kyhsgeekcode.disassembler D/TooLargeTool: MainActivity.onSaveInstanceState wrote: Bundle151272262 contains 9 keys and measures 3.9 KB when serialized as a Parcel
    * com.google.app_measurement.screen_service = 0.2 KB
    * android:viewHierarchyState = 1.7 KB
    * android:support:fragments = 1.1 KB
    * android:support:request_indicies = 0.1 KB
    * androidx.lifecycle.BundlableSavedStateRegistry.key = 0.1 KB
    * android:support:request_fragment_who = 0.2 KB
    * android:lastAutofillId = 0.1 KB
    * android:fragments = 0.4 KB
    * android:support:next_request_index = 0.1 KB
2020-03-07 23:56:32.506 17474-17474/com.kyhsgeekcode.disassembler E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1631520)
2020-03-07 23:56:32.507 17474-17474/com.kyhsgeekcode.disassembler W/ActivityStopInfo: Bundle stats:
2020-03-07 23:56:32.508 17474-17474/com.kyhsgeekcode.disassembler W/ActivityStopInfo:   android:viewHierarchyState [size=1768]
2020-03-07 23:56:32.509 17474-17474/com.kyhsgeekcode.disassembler W/ActivityStopInfo:     android:views [size=1720]
2020-03-07 23:56:32.527 17474-17474/com.kyhsgeekcode.disassembler W/ActivityStopInfo:   android:support:fragments [size=1628416]
2020-03-07 23:56:32.528 17474-17474/com.kyhsgeekcode.disassembler W/ActivityStopInfo: PersistableBundle stats:
2020-03-07 23:56:32.528 17474-17474/com.kyhsgeekcode.disassembler W/ActivityStopInfo:   [null]
2020-03-07 23:56:32.528 17474-17474/com.kyhsgeekcode.disassembler D/AndroidRuntime: Shutting down VM
2020-03-07 23:56:32.535 17474-17474/com.kyhsgeekcode.disassembler E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kyhsgeekcode.disassembler, PID: 17474
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1631520 bytes
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.os.TransactionTooLargeException: data parcel size 1631520 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1127)
        at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4027)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2020-03-07 23:56:32.546 17474-17474/com.kyhsgeekcode.disassembler I/PermissionUtils: Has permissions
2020-03-07 23:56:32.568 17474-17496/com.kyhsgeekcode.disassembler I/de.disassemble: Background concurrent copying GC freed 36296(1679KB) AllocSpace objects, 20(6MB) LOS objects, 15% free, 33MB/39MB, paused 706us total 139.397ms
2020-03-07 23:56:32.582 17474-17474/com.kyhsgeekcode.disassembler E/Disassembler: UncaughtException
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1631520 bytes
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.os.TransactionTooLargeException: data parcel size 1631520 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1127)
        at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4027)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
