### ISSUE TITLE
Version 1.3.1 crash report

### ISSUE THREAD

**Issue by mscalindt** [KYHSGeekCode/Android-Disassembler#34]
This version loads the UI before getting the required permission, resulting in crash on first start. I even got logcat:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kyhsgeekcode.disassembler/com.kyhsgeekcode.disassembler.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at com.kyhsgeekcode.disassembler.ColorHelper.<init>(ColorHelper.java:92)
	at com.kyhsgeekcode.disassembler.MainActivity.onCreate(MainActivity.java:1113)
	at android.app.Activity.performCreate(Activity.java:7009)
	at android.app.Activity.performCreate(Activity.java:7000)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
	... 9 more

**Comment by KYHSGeekCode** [comment]
You're right. Thanks for the report! I will fix that in the next release.

2018년 11월 20일 (화) 오후 7:09, Dimitar Yurukov <notifications@github.com>님이 작성:
