### ISSUE TITLE
Version 1.3.2 issue

### ISSUE THREAD

**Issue by mscalindt** [KYHSGeekCode/Android-Disassembler#37]
For some reason this version didn't ask me for storage permission, so on first start it crashed. On the next starts it just loads empty activity due to no storage permission. It doesn't ask for permission at all. Here is also a logcat for the first start (I know it is useless):

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kyhsgeekcode.disassembler/com.kyhsgeekcode.disassembler.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.kyhsgeekcode.disassembler.ListViewAdapter.addAll(java.util.ArrayList)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.kyhsgeekcode.disassembler.ListViewAdapter.addAll(java.util.ArrayList)' on a null object reference
	at com.kyhsgeekcode.disassembler.MainActivity.setupListView(MainActivity.java:1579)
	at com.kyhsgeekcode.disassembler.MainActivity.onCreate(MainActivity.java:1436)
	at android.app.Activity.performCreate(Activity.java:7009)
	at android.app.Activity.performCreate(Activity.java:7000)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
	... 9 more

**Comment by KYHSGeekCode** [comment]
Thank you, fixed it!
